//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furkan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Cid { get; set; }
        public string Cname { get; set; }
        public Nullable<int> Classhour { get; set; }
        public Nullable<int> Credit { get; set; }
        public string DepartmentName { get; set; }
    }
}
