//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furkan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string Sid { get; set; }
        public string password { get; set; }
        public string Tid { get; set; }
        public int Lid { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
