//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furkan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Mno { get; set; }
        public string Sid { get; set; }
        public string Sname { get; set; }
        public string Midterm { get; set; }
        public string Final { get; set; }
        public Nullable<int> Cid { get; set; }
        public string Status { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
